@startuml

class AbstractHouse{
buildBasic():void
buildWalls():void
roofed():void
build():void
}

class CommonHouse
class HighBuilding

AbstractHouse <|-- CommonHouse
AbstractHouse <|-- HighBuilding

@enduml